DARK_97_validacja_terminu_turnieju
DARK-development-team/DARK pull request #43
Opened 2021-05-19 11:13 UTC by shuntrho

Dodałem sprawdzanie, czy start_date < end_date co wyświetla odpowiedni komunikat w formularzu.

2021-05-19 12:30 UTC, BlqMary requested changes
Komunikat jest cacy i działa w 99% przypadków. Został jeszcze skrajny przypadek do obsłużenia , który aktualnie wywala błąd, czyli `start date = end date`.

2021-05-19 15:56 UTC, Tumilok reviewed
Jest spoko tylko jedna poprawka.

2021-05-19 15:56 UTC, Tumilok commented on dark/forms/tournament/add.py
> +            raise ValidationError('Start date must be before end date')
Tą linijke kodu raczej trzebausunąć, bo `self.add_error('start_date', 'Start date must be before end date') wypisuje błąd konkretnego field'u, a `raise ValidationError('Start date must be before end date')` wypisuje błąd pod całym formularzem. Chociaż i widzimy ze strony frontu błąd tylko raz (bo nie wyświetlamy błędów drugiego rodzaju), ale on jest wysyłany dwa razy i jak w przyszłości będziemy chcieli wyświetlać dodatkowo drugi rodzaj błędów, to może to spowodować zamieszanie

2021-05-22 10:33 UTC, Tumilok commented
Poprawiłem wszystkie uwagi, teraz powinno działać dobrze.

2021-05-22 10:34 UTC, Tumilok approved these changes

2021-05-22 12:13 UTC, BlqMary approved these changes

2021-05-22 19:10 UTC, merged