DARK84_dostęp_do_turniejów_oraz_jego_składowych
DARK-development-team/DARK pull request #44
Opened 2021-05-19 18:28 UTC by Tumilok

# Ograniczenie dostępu do turniejów oraz jego składowych

## Co zostałe dodane

### Backend
W pliku `dark/common/views.py` dodałem trzy mixin'y, które sprawdzają turnieji lub kolejki i uniemożliwiają dostęp do widoków (do których mixiny zostały dodane) ze strony backend.

* `TournamentEditableMixin` - widoki z tym mixin'em są dostępne jeżeli odpowiedni turniej jest **upcoming**, w przypadkach **in progress** oraz **archived** dostęp do takich widoków jest zaboroniony (Jest używany w widokach modyfikacji zespołów)
* `RoundAddableMixin` - widoki z tym mixin'em są dostępne jeżeli odpowiedni turniej jest **upcoming** lub **in progress**, w przypadku **archived** dostęp do takich widoków jest zaboroniony. (Jest używany tylko w widoku dodawania nowego turnieju)
* `RoundEditableMixin` - widoki z tym mixin'em są dostępne jeżeli odpowiednia runda jeszcze nie rozpoczęła się, w pozostałych przypadkach dostęp do takich widoków jest zaboroniony. (Jest używany w widokach edycji botów)

### Frontend
Dodatkowo do widoków dodałem dodatkowe zmienie, za pomocą których usuwam dostęp do niektórych żeczy ze strony frontend.

## Co warto przetestować (zaznaczajcie punkty które przetestowaliście, żeby nie robić to samo dziesięć razy)
[ ]

2021-05-20 16:29 UTC, BlqMary reviewed
Fajnie że poblokowany jest ten dostęp i nie można już wszystkiego zawsze zmieniać jako każdy użytkownik. Mam tylko jedną uwagę - fajnie by było jakby można było dodać bota przed startem rundy, a nie tylko w trakcie jej trwania (Tym bardziej jeśli runda ma się uruchamiać o zadanym czasie automatycznie, bo wtedy nie będzie kiedy dodać tego bota)

2021-05-22 09:12 UTC, Tumilok commented
> 
> 
> Fajnie że poblokowany jest ten dostęp i nie można już wszystkiego zawsze zmieniać jako każdy użytkownik. Mam tylko jedną uwagę - fajnie by było jakby można było dodać bota też przed startem rundy, a nie tylko w trakcie jej trwania (Tym bardziej jeśli runda ma się uruchamiać o zadanym czasie automatycznie, bo wtedy nie będzie kiedy dodać tego bota)

Słuszna uwaga, nie zauważyłem tego xd

2021-05-26 12:38 UTC, BlqMary approved these changes
Super!

2021-05-29 23:25 UTC, TheTryton requested changes

2021-06-03 16:13 UTC, TheTryton approved these changes

2021-06-03 16:38 UTC, merged