DARK117_showing_round_results
DARK-development-team/DARK pull request #47
Opened 2021-05-24 13:46 UTC by shuntrho

Dodałem wyświetlanie wyników rundy w nieco przystępniejszej formie.

2021-05-25 08:29 UTC, Tumilok requested changes
Mam parę uwag odnośnie funkcjonalności kodu:
1. U mnie nie działa pobieranie logów w obu formatach, ale nie jestem pewny czy to tylko mój problem więc proszę kogoś jeszcze to sprawdzić.
2. Przyciski `Pobierz plik .log` oraz `Pobierz plik .json` nie bardzo wpisują się w format anglojęzyczny naszej apki.
3. Mi się nie bardzo podoba format wyświetlana wyników. Chodzi mi o to że jakoś dziwnie to jest wypisane, najpierw nazwa głównej klasy bota, potem dlaczegoś w nawiasach nazwa rundy i na tylko na koniec nazwa zespołu. Ja bym raczej zostawił tylko nazwę teamu, bo wiadomo który jest round, a klasa główna botu nie ma sensu, bo od zespołu nie może uczestniczyć więcej niż jeden bot.
4. Jest wypisany tytuł `Scores`, a niżej `Final Scores`. Raczej coś z tego trzeba usunąć
5. Wrócić z powrotem pliki które nie są niezbędne do modyfikowania

![image](https://user-images.githubusercontent.com/44002074/119465397-ea856000-bd43-11eb-8e05-5e9cf312ed05.png)

2021-05-25 08:29 UTC, Tumilok commented on dark/templates/dark/teams/user_all.html
> -
Najlepiej nie modyfikować pliki jak nie ma na to potrzeby. Łatwiej to będzie potem migrować. Więc jabym raczej dodał linijkę z powrotem

2021-05-25 08:29 UTC, Tumilok commented on dark/templates/dark/tournament/all.html
> +
To samo i tutaj

2021-05-25 08:29 UTC, Tumilok commented on dark/templates/dark/tournament/info.html
> +
Tu też :)

2021-05-25 08:29 UTC, Tumilok commented on dark/urls/tournament/tround/sites.py
> +
I tutaj

2021-05-25 08:29 UTC, Tumilok commented on dark/views/platform/add.py
> -
Tutaj też

2021-05-25 08:29 UTC, Tumilok commented on dark/views/tournament/tround/info.py
> +        print(context['log_file_path'])
Czy te printy służą celom debugowym? Jeśli tak, to ich raczej trzeba usunąć

2021-05-26 06:54 UTC, shuntrho commented
W commicie 'enchanced results presentation' poprawiłem wyświetlanie więc powinno się to nieco lepiej prezentować.

2021-06-02 10:46 UTC, shuntrho commented on dark/urls/tournament/tround/sites.py
> +
Tutaj pycharm podpowiada dwie linie.

2021-06-02 15:22 UTC, Tumilok commented on dark/urls/tournament/tround/sites.py
> +
Wiem wiem, mi się po prostu wydaje się, że takie rzeczy najlepiej poprawiać podczas pracy nad plikiem, i nie warto modyfikować cały plik żeby dodać czy usunąć jedną linijkę. Ale spoko, niech zostanie

2021-06-02 15:31 UTC, Tumilok approved these changes
Poprawki wyglądają fajnie i pobieranie działa!!!

2021-06-03 12:48 UTC, merged