DARK53_heroku_deploy
DARK-development-team/DARK pull request #48
Opened 2021-05-26 06:50 UTC by shuntrho

Zrobiłem deploya, co wymagało kilku zmian w ustawieniach i dodania pliku wsgi.py
Po zmergowaniu do developa dodam zapewne automatyczny deploy.

Link: https://darkplatform.herokuapp.com/

2021-05-26 12:28 UTC, BlqMary reviewed
Taki błąd mi się pojawia na kilku stronach (wchodzenie do szczegółów rundy, dodawanie rundy), nie wiem czy to kwestia źle dodanej platformy czy czegoś innego...
![image](https://user-images.githubusercontent.com/50996654/119659402-69ef5e00-be2e-11eb-8086-d22e5523951b.png)

2021-05-29 17:30 UTC, TheTryton requested changes

2021-05-29 17:30 UTC, TheTryton commented on dark/wsgi.py
> +application = get_wsgi_application()
do tej linijki wszystko jest kopią z base/wsgi.py - import

2021-06-02 07:20 UTC, shuntrho commented on dark/wsgi.py
> +application = get_wsgi_application()
Przeniosłem wsgi.py z base/ do dark/

2021-06-02 07:20 UTC, merged